[PIL-802][DG]Adding contact Details & Print on final CYA page
hmrc/pillar2-acceptance-tests pull request #188
Opened 2024-04-23 16:00 UTC by dhirenganvir

2024-04-23 16:06 UTC, neelu-dwivedi reviewed
Can you add this scneario in any of the existing feature file for RFM journey rather than creating a new for 1 scenario?

2024-04-24 13:39 UTC, neelu-dwivedi approved these changes

2024-04-24 14:09 UTC, srikanthhmrc requested changes

2024-04-24 14:09 UTC, srikanthhmrc commented on src/test/resources/features/RFMFinalReviewCYAPage.feature
> +
can we remove extra spaces

2024-04-24 14:16 UTC, srikanthhmrc requested changes

2024-04-24 14:16 UTC, srikanthhmrc commented on src/test/scala/uk/gov/hmrc/test/ui/cucumber/stepdefs/CommonFunctions.scala
> +      case "RFM Second Contact Address Page"      => RFMSecondContactAddressPage
remove the duplicate step

2024-04-24 14:16 UTC, srikanthhmrc commented on src/test/resources/features/RFMFinalReviewCYAPage.feature
> +@tests
can we put this back in RFMCYAPage.feature file

2024-04-24 14:16 UTC, srikanthhmrc commented on src/test/resources/features/RFMFinalReviewCYAPage.feature
> +    And The Heading should be Review and submit
need to remove content verification steps and make sure that these are covered in unit tests as per HMRC test leads suggestion

2024-04-25 07:58 UTC, annemonica5 approved these changes

2024-04-25 14:55 UTC, merged