PIL- 1008 refactor RFM journey and reduce duplicates
hmrc/pillar2-acceptance-tests pull request #218
Opened 2024-06-19 08:05 UTC by neelu-dwivedi

2024-07-02 10:50 UTC, srikanthhmrc requested changes

2024-07-02 10:50 UTC, srikanthhmrc commented on src/test/resources/features/RFMGRSflowPages.feature
> +    And I click on Continue button
please check with one of the devs , whether this content is covered in unit testing and get rid of content testing in ATs

2024-07-12 15:12 UTC, neelu-dwivedi commented
Moved Agent journeys to @batch1 as batch3 is taking long time to run.

2024-07-12 15:16 UTC, annemonica5 approved these changes

2024-07-15 07:31 UTC, srikanthhmrc commented on src/test/resources/features/RFMGRSflowPages.feature
> +    Then I should see an error message Enter name of the person of team we should contact on the RFM second contact name Page
this error message should cover in unit tests

2024-07-16 15:18 UTC, srikanthhmrc approved these changes

2024-07-17 08:31 UTC, merged