PIL-221-Fixed Acceptance test
hmrc/pillar2-acceptance-tests pull request #3
Opened 2023-04-21 13:41 UTC by AKKUM

2023-04-21 14:03 UTC, srikanthmeurostar requested changes

2023-04-21 14:03 UTC, srikanthmeurostar commented on src/test/resources/features/CheckAnswers.feature
> +    And I select value_0 and continue
can we provide the option text here instead value_0

2023-04-21 14:03 UTC, srikanthmeurostar commented on src/test/resources/features/TradingBusiness.feature
> +    And I select value_0 and continue
same here

2023-04-21 16:51 UTC, srikanthhmrc commented on src/test/resources/features/CheckAnswers.feature
> +    And I select value_0 and continue
can we mention the option to be selected instead value_0

2023-04-21 16:51 UTC, srikanthhmrc commented on src/test/resources/features/TradingBusiness.feature
> +    And I select value_0 and continue
same here

2023-04-24 10:03 UTC, nitin-srivastav approved these changes

2023-04-24 10:03 UTC, merged